### ISSUE TITLE
Auto-set Initial climb doesn't work

### ISSUE THREAD

**Issue by mjpikat** [rpuig2001/InitialCimbPlugin#1]
Can you explain how should it work?
On label assume it doesn't change anything automatically, neither when DEP list is populated.

**Comment by rpuig2001** [comment]
Do you have the file configured and Initial climb item in the departure list?

**Comment by mjpikat** [comment]
The file is configured, however the initial climb item is not in the list. Shall it be there? (and which item) because if I add the item, on click to CFL it works, but I expect the plugin to set CFL automatically without any extra clicks.

**Comment by mjpikat** [comment]
I just tested by adding the Initial Climb item (without any left/right click option) and it seemed to work 🥇
