### ISSUE TITLE
Plugin not working ES v3.2.3

### ISSUE THREAD

**Issue by owner7913** [rpuig2001/InitialCimbPlugin#3]
Got an update, and suddently the plugin wont regonize the SID, and just remains blank?

**Comment by rpuig2001** [comment]
Any update has been released for the plugin and it works fine in latest ES release.

**Comment by owner7913** [comment]
So here is my xml file:
![xml file](https://github.com/rpuig2001/InitialCimbPlugin/assets/109968864/5f4216ef-e1fc-4e23-a0d8-864768849c85)
Here is how it look like in plugins in ES:
![ESplugin](https://github.com/rpuig2001/InitialCimbPlugin/assets/109968864/e8ddc08d-a2cf-49e9-9057-6c6bf2b6d791)
And here is my depature list, INI is blank:
![Depature](https://github.com/rpuig2001/InitialCimbPlugin/assets/109968864/f2f4530b-4f3c-4d07-9b10-df78041444bd)

**Comment by owner7913** [comment]
I love this plugin, and if you got any suggestion on why it wont work?

**Comment by rpuig2001** [comment]
> I love this plugin, and if you got any suggestion on why it wont work?

No problem, can you send me your xml file to take a look what could be going on?

**Comment by owner7913** [comment]
[initialClimb.txt](https://github.com/rpuig2001/InitialCimbPlugin/files/11584413/initialClimb.txt)
Made it a txt file xml is not supported for upload

**Comment by rpuig2001** [comment]
Hi @owner7913,
Please check the validation of your xml.
Attached below the corrected xml (some nodes were not closed).
[initialClimb.txt](https://github.com/rpuig2001/InitialCimbPlugin/files/11585141/initialClimb.txt)

**Comment by owner7913** [comment]
Thanks for the help it's now working!
