### ISSUE TITLE
Change CFL to initial climb without adding it to departure list

### ISSUE THREAD

**Issue by cptalpdeniz** [rpuig2001/InitialCimbPlugin#4]
Hello Roger,

Is it possible to change CFL to the initial climb (like in Virtual Controller Assistant) without adding it to departure list? The way this plugin used to work was that when you selected the runway, it would match it with RWY+SID and change the CFL automatically. Can this be achieved?

Regards,
CC @gurselalp

**Comment by cptalpdeniz** [comment]
Just wanted to follow up and see if you had a chance to take a look at this? @rogerpuig11

**Comment by rpuig2001** [comment]
Hi @cptalpdeniz,
Unfortunately I didn't but I will take a look asap :)

**Comment by rpuig2001** [comment]
Hi @cptalpdeniz,
I made an implementation, but testing it I can see that if you hide the column from the "F" option of the desired list, then the RFL is set too.
Does it works for you?

**Comment by cptalpdeniz** [comment]
> ...if you hide the column from the "F" option of the desired list, then the RFL is set too. Does it works for you?

We use RFL for cruise (as the requested level), is it possible for it to only change CFL (temporary alt)?

**Comment by rpuig2001** [comment]
> > ...if you hide the column from the "F" option of the desired list, then the RFL is set too. Does it works for you?
> 
> We use RFL for cruise (as the requested level), is it possible for it to only change CFL (temporary alt)?

Yes sorry I mean the CFL instead of the RFL

**Comment by cptalpdeniz** [comment]
If it changes CFL without adding a new column to the departure list, that is exactly what we are looking for. Is it possible to test it and provide feedback?

**Comment by rpuig2001** [comment]
> If it changes CFL without adding a new column to the departure list, that is exactly what we are looking for. Is it possible to test it and provide feedback?

Disabling the column from the "F" of the list doesn't work?
Otherwise I'll finish the implementation.

**Comment by rpuig2001** [comment]
Hi @cptalpdeniz,
below attached v1.6.0 to test it 👍 
[InitialClimbPlugin.zip](https://github.com/rpuig2001/InitialCimbPlugin/files/12841749/InitialClimbPlugin.zip)

**Comment by cptalpdeniz** [comment]
Give me about 15 minutes please, I'm testing it currently.

**Comment by cptalpdeniz** [comment]
I just added the plugin to our sector file, I made a small trial at LTFM after editing the initialClimb.xml. Without changing anything on the sector file, it did work! Only feedback I could give was VCA did set this up almost instantly however I've observed InitialClimb plugin has about 1-8 second delay. Can that be shortened down?

**Comment by rpuig2001** [comment]
Thanks @cptalpdeniz,
Let's give it a try to the one attached below :)
[InitialClimbPlugin.zip](https://github.com/rpuig2001/InitialCimbPlugin/files/12847437/InitialClimbPlugin.zip)

**Comment by cptalpdeniz** [comment]
As per the tests, it worked exactly as needed!

Thank you so much!

**Comment by rpuig2001** [comment]
Thank you, I will close this issue and release it as v1.6.0.
Thanks for the fast testing and collaboration :)

**Comment by cptalpdeniz** [comment]
Thank you for all the help and the plugins! Helps us a lot. Much appreciated!
